cargo-features = ["panic-immediate-abort"]

[package]
name = "ascalon-client"
version = "0.1.0"
edition = "2024"

[features]
dev = ["bevy/free_camera"]

[dependencies]
bitflags = "2"
uuid = "1"
zerocopy = "0.8"

bevy = { git = "https://github.com/bevyengine/bevy.git", rev = "1a6377e33b26b6d744f96e35dbe9392e86602ac3", features = ["2d", "3d", "ui"] }

ascalon-asset = { path = "../ascalon/asset" }
#ascalon-asset = { git = "https://github.com/valaphee/ascalon.git", rev = "3bf978473f50710c57f0f3b1a9a18df3e33a4eee" }
ascalon-network = { git = "https://github.com/valaphee/ascalon.git", rev = "3bf978473f50710c57f0f3b1a9a18df3e33a4eee" }
ascalon-protocol = { git = "https://github.com/valaphee/ascalon.git", rev = "3bf978473f50710c57f0f3b1a9a18df3e33a4eee" }

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
#lto = true
codegen-units = 1
panic = "immediate-abort"
strip = "symbols"
