cargo-features = ["panic-immediate-abort"]

[package]
name = "ascalon-client"
version = "0.1.0"
edition = "2024"
description = "Unofficial Guild Wars 2 client"
license = "MIT"
repository = "https://github.com/valaphee/ascalon-client"

[dependencies]
bitflags = "2"
zerocopy = "0.8"

sha2 = "0.11"

bevy = { version = "0.20", features = ["2d", "3d", "ui", "free_camera"] }

ascalon-asset = { git = "https://github.com/valaphee/ascalon.git", rev = "112855ba425c316675a5b8baf8ce3536700313f6" }
ascalon-network = { git = "https://github.com/valaphee/ascalon.git", rev = "112855ba425c316675a5b8baf8ce3536700313f6" }
ascalon-protocol = { git = "https://github.com/valaphee/ascalon.git", rev = "112855ba425c316675a5b8baf8ce3536700313f6" }

[profile.dev]
opt-level = 1
debug = false

[profile.dev.package."*"]
opt-level = 3

[profile.release]
#lto = true
codegen-units = 1
panic = "immediate-abort"
strip = "symbols"
