use ascalon_asset::packfile::{Guid, Ptr, WcharPtr};

use super::{Item, Name};

#[derive(Debug)]
#[repr(C)]
pub struct Achievement {
    pub content_guid: Guid,
    pub content_type: u32,
    pub content_uid: u32,
    pub content_name: Ptr<Name>,
    pub content_full_name: Ptr<Name>,
    pub data_id: u32,
    pub _2c: u32,
    pub _30: WcharPtr,
    pub _38: u32,
    pub _3c: u32,
    pub _40: Ptr<Achievement>,
    pub _48: Ptr<()>,
    pub _50: Ptr<()>,
    pub _58: u32,
    pub _5c: u32,
    pub _60: Ptr<Item>,
    pub name: u32,
    pub description: u32,
    pub _70: u32,
    pub requirement: u32,
    pub _78: Ptr<()>,
    pub _80: u32,
    pub _84: u32,
    pub _88: Ptr<()>,
    pub _90: Ptr<()>,
    pub _98: u32,
    pub _9c: u32,
    pub _a0: u32,
    pub _a4: u32,
    pub _a8: Ptr<()>,
    pub _b0: u32,
    pub _b4: u32,
    pub _b8: u32,
    pub _bc: u32,
    pub _c0: Ptr<Item>,
    pub _c8: u32,
    pub _cc: u32,
    pub _d0: Ptr<()>,
    pub _d8: u32,
    pub _dc: u32,
    pub _e0: Ptr<()>,
    pub _e8: u32,
    pub _ec: u32,
    pub _f0: Ptr<()>,
    pub _f8: u32,
    pub _fc: u32,
}
