use super::{ItemDef, Name, ProgressDef};

#[repr(C)]
pub struct CraftingRecipeDef {
    pub contentGuid:      [u8; 16],
    pub contentType:      u32,
    pub contentUid:       u32,
    pub contentName:      *const Name,
    pub contentFullName:  *const Name,
    pub dataId:           u32,
    pub _2c:              u32,
    pub ingredients:      *const [()],
    pub outputItem:       *const ItemDef,
    pub outputItemCount:  u32,
    pub rating:           u32,
    pub _50:              u32,
    pub time:             u32,
    pub _58:              u32,
    _5c:                  u32,
    pub _60:              *const ProgressDef,
    pub _68:              *const (),
    _70:                  u32,
    _74:                  u32,
    pub guildIngredients: *const [()],
    pub item:             *const ItemDef,
    pub _90:              *const (),
    _98:                  u32,
    _9c:                  u32,
    _a0:                  u32,
    _a4:                  u32,
    pub _a8:              *const (),
}
